[phases.setup]
nixPkgs = ["php83", "php83Packages.composer", "php83Extensions.pdo_mysql", "git", 
  "nodejs"]

[phases.install]
cmd = """
composer install --no-dev --optimize-autoloader
npm ci
"""

[phases.build]
cmd = """
php artisan config:cache
php artisan route:cache
npm run build
"""

[start]
cmd = """
php artisan migrate --force
php artisan serve --host=0.0.0.0 --port=$PORT
"""